nuget13

diff --git a/.github/workflows/package_nuget.yml b/.github/workflows/package_nuget.yml
--- a/.github/workflows/package_nuget.yml
+++ b/.github/workflows/package_nuget.yml
@@ -57,17 +57,24 @@ jobs:
     - name: Verify .nupkg file
       run: |
         echo "Listing contents of ./nupkgs:"
-        ls -la ./nupkgs  # Usa 'ls -la' para obtener más detalles y ver si el archivo se generó correctamente
+        ls -la ./nupkgs  # Verificamos los archivos generados para asegurar que el .nupkg exista
 
     # Paso 9: Publicar el paquete NuGet en GitHub Packages
     - name: Publish NuGet Package to GitHub Packages
       run: |
-        dotnet nuget add source "https://nuget.pkg.github.com/mayrafc/index.json" \
-          --name github \
-          --username mayrafc \
-          --password ${{ secrets.GITHUB_TOKEN }} \
-          --store-password-in-clear-text
+        # Verificamos nuevamente que el archivo .nupkg existe antes de intentar la publicación
+        if [ -f ./nupkgs/*.nupkg ]; then
+          echo "Found .nupkg file, proceeding to push..."
+          dotnet nuget add source "https://nuget.pkg.github.com/mayrafc/index.json" \
+            --name github \
+            --username mayrafc \
+            --password ${{ secrets.GITHUB_TOKEN }} \
+            --store-password-in-clear-text
 
-        dotnet nuget push ./nupkgs/*.nupkg --source "github"
+          dotnet nuget push ./nupkgs/*.nupkg --source "github"
+        else
+          echo "No .nupkg file found, aborting publish step!"
+          exit 1  # Esto abortará la acción si no se encuentra el archivo
+        fi
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Este token es automático, no necesitas configurarlo manualmente.
